### PR TITLE
Add an uuid module

### PR DESCRIPTION
**Pull request by rhynomatt**
sorry, I don't know if it's bad etiquette to mirror someone else's PR :(
took the code from #59, tidied it up and added ulid and tests. a few notes:

1. I feel `uuid` is too restrictive a name for this module. maybe `random`?
2. should I squash some of the smaller fix commits?

### CODE REVIEW

**Comment by 1bardesign** [comment]
Probably would have been nice to include @josh-perry 's commits as-is, unless you have and I just can't see them for some reason? This way he doesn't get any attribution by the look of it.

I don't care about typo fixes etc being commits, messy history is better than fake history imo.

`random` isn't a great name but maybe `identifier` or similar?

would be good to just use `os.time` if no time function provided and `os` module is present.

**Comment by josh-perry** [comment]
Fwiw I don't mind at all that you took the PR I abandoned/forgot about but I'm not sure it's good etiquette either. :)

(+1 for `identifier` by the way)

**Comment by rhynomatt** [comment]
I couldn't get a clean rebase without messing up the blame, so I think it'd just be easier to cherry pick all commits from here into a new branch based on josh's fork, and pull request that.

**Comment by rhynomatt** [comment]
moved to #62.

**Pull request closed without merging**
