### PR TITLE
vec2: add meta functions for mathematical operators

### PR DESCRIPTION
**Pull request by billmakes**
As the title describes, this PR add's meta functions for mathematical operators.

addition:
`vec2(1, 2) + vec2(3, 4)` (4.00, 6.00)

subtraction:
`vec2(1, 2) - vec2(3, 4)` (-2.00, -2.00)

multiplication: 
`vec2(1, 2) * 2`  (2.00, 4.00)
`2 * vec2(3, 4)`  (6.00, 8.00)
`vec2(1, 2) * vec2(3, 4)` (3.00, 8.00)

division:
`vec2(4, 4) / 2`  (2.00, 2.00)

state_machine:
I added another field on the state_machine for the previous state name. This was a really small change and figured I would get input on that too while I'm here, though it probably should have been a separate PR... 

The use-case for me personally was using it to calculate unique behavior based on where we came from. For example I want to enter jump state from wallgrab state, but I want the velocity direction to be slightly tweaked in the jump state's update method if we came from wallgrab.

I find having these handy very useful and intuitive, let me know you're thoughts :)

### CODE REVIEW

**Comment by 1bardesign** [comment]
Separating the state machine stuff would be nice so it can be reviewed and commented on in isolation :pray: 

For meta functions/operator overloads on vec2 - i'm ok with this. The reason for using methods is that it encourages the possibility of upgrading to inplace versions which drastically reduces garbage churn, but I appreciate it's very wordy.

**Comment by 1bardesign** [comment]
I'd like to request that they go through the existing methods though rather than contain separate inline implementations. Also support for vector division probably makes sense.

**Comment by billmakes** [comment]
> I'd like to request that they go through the existing methods though rather than contain separate inline implementations. Also support for vector division probably makes sense.

Cool, that's actually a great idea. I updated the PR

**Comment by 1bardesign** [comment]
:+1: :tada:

**Pull request merged**
