### PR TITLE
Add luacheck and fix bugs it found

### PR DESCRIPTION
**Pull request by idbrii**
Setup a luacheck github action and configuration. Fix some legitimate bugs it discovered.

luacheck is pretty good at finding issues in lua code that a compiler would find in other languages. It has a lot of configuration options to control which warnings it emits. I've ignored a bunch of warnings and then added commits that fix the issues and remove those ignores. There are still a bunch of remaining warnings that are probably fine.

You can run it:

    luacheck .

You can see what the action output looks like:

* [Success](https://github.com/idbrii/love-batteries/runs/5411731898?check_suite_focus=true) (commit https://github.com/idbrii/love-batteries/commit/0c193d79019eb2d3fc25e7f0b5aa24197cb8b3ca has a little ✔️ )
* [Failure](https://github.com/idbrii/love-batteries/runs/5411990748?check_suite_focus=true) (commit: https://github.com/idbrii/love-batteries/commit/0d6076a3c8ebd3db6f29f0b87774064a9868b513 has a little ❌ )

With this PR, luacheck produces no warnings because any that occur are ignored in luacheckrc. (In each of these commits, luacheck runs clean because I'm only removing ignores that I fix.)

luacheck found two bugs: 

* crash when using append_inplace without batteries:export().
* circle_aabb_overlap wouldn't have the same results as
aabb_circle_overlap. (same for _collide)

### CODE REVIEW

**Comment by idbrii** [comment]
The remaining (ignored) warnings are mostly unused loop variables, long lines, and unused variables.

The only ones that I think are worth fixing are unused variables (since they are sometimes actual typo errors, but they require code style changes:

```
function vec2:normalise_inplace()
	local v, len = self:normalise_both_inplace()
	return v
end
function vec2:normalise_len_inplace()
	local v, len = self:normalise_both_inplace()
	return len
end
```

Becomes
```
function vec2:normalise_inplace()
	local v = self:normalise_both_inplace()
	return v
end
function vec2:normalise_len_inplace()
	local _, len = self:normalise_both_inplace()
	return len
end
```
(Although normalise_inplace becomes pretty redundant.)

**Comment by 1bardesign** [comment]
`normalise_inplace` not providing an argument you have to ignore will lead to fewer surprising results when passing it into other functions directly.

I've had mixed experience on luacheck and other linting, in the past but if it's run separately by github and we don't start dropping inline `--nonsense: make some external linker happy` comments through the actual code, I'm not fussed and happy to accept the work.

Either way, thanks for the various catches.

**Comment by 1bardesign** [comment]
unclear why it's complaining about using a parameter here https://github.com/1bardesign/batteries/runs/5732686737?check_suite_focus=true is there some rule we can change to fix it @idbrii ?

**Comment by idbrii** [comment]
@1bardesign 

>mathx.lua:129:24: used variable _r

It expects the convention where you prefix variables with _ to indicate that they're unused, but that example is using the variable.

```
local function _random(_r, ...)
	if _r then return _r:random(...) end
```

Could we change it to this (not sure what the underscore is indicating there):

```
local function _random(r, ...)
	if r then return r:random(...) end
```

----

To add an ignore:
1. Check the [list of warnings](https://luacheck.readthedocs.io/en/stable/warnings.html).
1. Search the list for the error message (minus any code snippets).
1. If not found, try searching for one of the words in the errror. The error messages don't always exactly line up with that list.
1. Add the number (214 in this case) to [luacheckrc's top `ignore` section](https://github.com/1bardesign/batteries/blob/cb3083bc79ec274d08499dfc7ced6f188295fb2d/.luacheckrc#L3-L8).

**Comment by 1bardesign** [comment]
We often use _ to signal private/internal use variables or fields.

If you could check https://github.com/1bardesign/batteries/commit/6e65f82474721e3f3f6ffe6ad2781f542e964637 that'd be great; I've added the ignore and clarified the variable name. I still need to sort out the naming of the deliberately reused locals in `colour.lua`, but that's unrelated.

**Comment by idbrii** [comment]
Yeah, looks good.

**Pull request merged**
