### PR TITLE
Added color.hex2RGB

### PR DESCRIPTION
**Pull request by flamendless**
Simple usage sample:

```lua
print(color.hex2RGB("#ffffff") --255, 255, 255
print(color.hex2RGB("ffffff") --255, 255, 255
```

### CODE REVIEW

**Comment by flamendless** [comment]
I'll leave the documentation in the source code to you @1bardesign

**Comment by 1bardesign** [comment]
Looks like it's based on a slightly old version from the method names, haha.

I'm not sure of the benefit of a string version over the current number based ones?

Eg [colour.unpack_rgb](https://github.com/1bardesign/batteries/blob/master/colour.lua#L28) can be used like `colour.unpack_rgb(0xff00ff)` to get that terrible debug magenta, with no string garbage generated...

**Comment by flamendless** [comment]
My usage is that we could run it like a script getting input from user like
```lua
lua script.lua "#ffffff"
```

but if Lua could pass the `0xffffff` and Batteries convert that, that's easier.

Nevermind this PR then haha

**Comment by 1bardesign** [comment]
:+1:

**Pull request closed without merging**
